config/routes.rb
Site::Application.routes.draw do

  root "pages#home"

  get 'about' => "pages#about"
  get 'events' => "pages#events"
  get 'media' => "pages#media"
  get 'art' => "pages#art"
  get 'music' => "pages#music"
  get 'store' => "pages#store"

  resources :books

  

end

app/models/book.rb
class Book < ActiveRecord::Base
  validates :slug, :presence => true, :uniqueness => true

  acts_as_url :short_title, :url_attribute => :slug, :only_when_blank => true

  def to_param
    slug
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @books = Book.all
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render action: 'show', status: :created, location: @book }
      else
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:short_title, :long_title, :sub_title, :image, :publishing, :description, :slug)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def events
  end

  def books
  end

  def media
  end

  def art
  end

  def music
  end

  def store
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(content)
    m ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    m.render(content).html_safe
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="books">
  <h2>My Books</h2>
  <%= image_tag 'writer1-large.jpg', { class: 'bordered' } %>

  <div class="two-column clearfix">
    <div class="column">
      <div class="heading">Book titles</div>
      <% @books.each do |book| %>
        <%= link_to book.short_title, book %><br>
      <% end %>
    </div>
  </div>
</div>
    

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<h2><%= @book.long_title %></h2>
<h3><%= @book.sub_title %></h3>
<div class="two-column clearfix">
  <div class="column">
    <div class="heading">Book titles</div>
    <% @books.each do |book| %>
      <%= link_to book.short_title, book %><br>
    <% end %>
  </div>

  <div class="column">
    <%= image_tag "/uploads/books/#{@book.image}" %>
    <%= markdown(@book.description) %>
  </div>
</div>
<%= link_to 'Back', books_path %>

app/views/layouts/_nav.html.erb
<nav class="nav">
  <ul>
    <li><%= link_to 'home', root_path %></li>
    <li><%= link_to 'about', about_path %></li>
    <li><%= link_to 'events', events_path %></li>
    <li><%= link_to 'books', books_path %></li>
    <li><%= link_to 'media', media_path %></li>
    <li><%= link_to 'art', art_path %></li>
    <li><%= link_to 'music', music_path %></li>
    <li><%= link_to 'store', store_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Site</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="logo"><%=image_tag 'customLogo.jpeg' %></div>
      <%= render 'layouts/nav' %>
    </div>
    <div class="content <%= controller.action_name %>">
      <%= yield %>
    </div>
  </div>


</body>
</html>

app/views/pages/about.html.erb
<h2>About me</h2>
<div class="two-column clearfix">
  <div class="column left">
    <%= image_tag 'Salisbury_sm-medium.jpg' %>
    <div class="contact">
      <strong>Ranchor Prime</strong><br>
      10 Grafton Mews, London W1T 5JG, UK<br>
      write to ranchorprime at gmail.com
    </div>
  </div>

  <div class="column">
    <p>I write about spirituality, publish my own and other people's books, and teach Bhagavad Gita.</p>

    <p>I was born Richard Prime in 1950 and grew up in Sussex, where I roamed the woods and explored the streams (still my favourite pastime). My father was a doctor and my mother a businesswoman.</p>

    <p>I was an art student in Chelsea in 1970 when I discovered the Bhagavad Gita and met followers of Krishna. I joined the Radha Krishna Temple and became a disciple of A C Bhaktivedanta Swami. In 1971 I was given the name Ranchor Das. During the 1970s I pioneered a Hare Krishna centre in Manchester, painted pictures, and built and managed a new Radha Krishna temple in the West End of London. In 1987 I began working as an adviser to WWF, the World Wide Fund for Nature, on religion and conservation.</p>

    <p>My first book, Hinduism and Ecology, written in 1990, arose from my work with WWF in Britain and India. This led me to found Friends of Vrindavan, an environmental charity for conserving the sacred forests of Krishna in India and strengthening the link between Hinduism and ecology. In 1996 I helped found ARC, the Alliance of Religions and Conservation, which works with religions worldwide to support environmental education and action.</p>

    <p>I started Fitzrovia Press in October 2008 to publish my own books and new writing from other authors. The press is dedicated to producing spiritual books for a broad readership.</p>
  </div>
</div>

app/views/pages/art.html.erb
<h1>Pages#art</h1>
<p>Find me in app/views/pages/art.html.erb</p>

app/views/pages/events.html.erb
<h1>Events</h1>
<h2>EVENTS in 2014: Talks, classes, workshops and kirtan</h2>

<h3>Home classes every Wednesday evening</h3>
<%= image_tag 'studio_panorama_sm.jpg', { class: 'bordered' } %>
<p><span class="highlight">Weekly Bhagavad Gita chanting and discussion</span> - in my garden studio in Fitzrovia. Classes begin and end with devotional chanting and allow time for questions and discussion. The ancient poem of 700 Sanskrit verses offers a deep understanding of life relevant to the beginner as much as to the advanced yogi.<br>
At my home, 10 Grafton Mews W1T 5JG.<br>
Classes are open to all.<br>
Every Wednesday 7pm-8.30pm<br>
Suggested donation £5</p>

<p>&nbsp;</p>

<h3>Brighton Satsang: Hearing the Inner Voice</h3>
<p>An introduction to the Bhagavad Gita in four sessions<br>
<strong>First session: Knowledge of the self: Jnana Yoga</strong><br>
The self is eternal and indestructible, without beginning or end. At the end of life the self is carried into another body in the continuing cycle of rebirth.<br>
With time for questions and discussion, and closing with devotional chanting.<br> 
<strong>16th February, 7pm-8pm, Jing Massage Institute, 28/29 Bond Street, Brighton</strong> <em>(by donation)</em><br>
Details here: <%= link_to 'www.brightonyoga.org', '//www.brightonyoga.org', { target: :blank } %></p>

app/views/pages/home.html.erb
<%= image_tag 'Ranchor_Jivamukti_sanskrit.jpg', { class: 'bordered' } %>

<div class="contact">Contact: 10 Grafton Mews, London W1T 5JG  +44 (0)7743 898470</div>

app/views/pages/media.html.erb
<h1>Pages#media</h1>
<p>Find me in app/views/pages/media.html.erb</p>

app/views/pages/music.html.erb
<h1>Pages#music</h1>
<p>Find me in app/views/pages/music.html.erb</p>

app/views/pages/store.html.erb
<h1>Pages#store</h1>
<p>Find me in app/views/pages/store.html.erb</p>